### ISSUE TITLE
Creacion de Usuarios

### ISSUE THREAD

**Issue by xaviflores21** [FCMAK/.github#1]

**Comment by rickypazd** [comment]
Fallo cuando lo probe al registrar el usuario
<img width="608" alt="Screenshot 2024-05-21 at 23 12 28" src="https://github.com/FCMAK/.github/assets/35882906/317922ee-78b8-460d-a02f-949c8a1eefee">



Registro.js:144 Uncaught ReferenceError: values is not defined
    at Object.onSubmit (Registro.js:144:21)
    at SForm.submit (index.js:334:1)
    at Object.onPress (Registro.js:268:52)
    at onPress (index.tsx:43:32)
    at onClick (PressResponder.js:364:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
onSubmit @ Registro.js:144
SForm.submit @ index.js:334
onPress @ Registro.js:268
onPress @ index.tsx:43
onClick @ PressResponder.js:364
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
Show 17 more frames
Show less
Registro.js:144 Uncaught ReferenceError: values is not defined
    at Object.onSubmit (Registro.js:144:21)
    at SForm.submit (index.js:334:1)
    at Object.onPress (Registro.js:268:52)
    at onPress (index.tsx:43:32)
    at onClick (PressResponder.js:364:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)

**Comment by rickypazd** [comment]
Ya lo correji
